name: Build

on:
  workflow_dispatch:

  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:

      - uses: lukka/get-cmake@latest

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            C:/Program Files/LLVM
            ${{ runner.temp }}/llvm
          key: llvm-15.0

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
          directory: ${{ runner.temp }}/llvm

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cmake
        run: cmake -S. -B build -DLT_LLVM_INSTALL_DIR=${{ env.LLVM_PATH }} -D CMAKE_CXX_COMPILER=$LLVM_PATH/bin/clang++ -D CMAKE_C_COMPILER=$LLVM_PATH/bin/clang

      - name: Make Example
        run: make -C build

      - name: Make Example LLVM-IR
        run: make -C build sim_dis sim_c_dis
